clusterGroup:
  name: hub
  isHubCluster: true
  # Note: setting this to true stores the vault unseal keys inside a cluster secret and
  # is fundamentally insecure
  insecureUnsealVaultInsideCluster: true

  namespaces:
  - open-cluster-management
  - vault
  - golang-external-secrets
  - config-demo
  - data-plane
  - control-plane
  - zta-sso
  - openshift-operators-redhat
  - openshift-compliance

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.5
      csv: advanced-cluster-management.v2.5.0
  
    jaegar:
      name: jaeger-product
      source: redhat-operators
      channel: stable
      csv: jaeger-operator.v1.36.0-2

    elastic:
      name: elasticsearch-operator
      source: redhat-operators
      channel: stable
      csv: elasticsearch-operator.5.5.2


    kiali-ossm:
      name: kiali-ossm
      source: redhat-operators
      channel: stable
      csv: kiali-operator.v1.48.2

    servicemeshoperator:
      name: servicemeshoperator
      source: redhat-operators
      channel: stable
      csv: servicemeshoperator.v2.2.2

    openshift-compliance:
      name: compliance-operator
      namespace: openshift-compliance
      channel: release-0.1

    rhacs-operator:
      name: rhacs-operator
      source: redhat-operators
      channel: latest
      csv: rhacs-operator.v3.71.0

    rhsso-operator:
      name: rhsso-operator
      namespace: zta-sso
      source: redhat-operators
      channel: stable
      csv: rhsso-operator.7.5.1-opr-005

  projects:
  - hub
  - config-demo
  - control-plane
  - data-plane

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
          - /spec/loggingCA

    vault:
      name: vault
      namespace: vault
      project: hub
      chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: v0.20.1
      overrides:
      - name: global.openshift
        value: "true"
      - name: injector.enabled
        value: "false"
      - name: ui.enabled
        value: "true"
      - name: ui.serviceType
        value: LoadBalancer
      - name: server.route.enabled
        value: "true"
      - name: server.route.host
        value: null
      - name: server.route.tls.termination
        value: edge
      - name: server.image.repository
        value: "registry.connect.redhat.com/hashicorp/vault"
      - name: server.image.tag
        value: "1.10.3-ubi"

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    compliance-operator:
      name: compliance-operator
      namespace: openshift-compliance
      project: hub
      path: charts/hub/compliance-operator

    config-demo:
      name: config-demo
      namespace: config-demo
      project: config-demo
      path: charts/all/config-demo

    sm-apps:
      name: sm-apps
      namespace: data-plane
      project: data-plane
      path: charts/all/sm-apps

      #sm-control-plane:
      #name: control-plane
      #namespace: control-plane
      #project: control-plane
      #path: charts/all/sm-control-plane
        
  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs:
    - name: regional-ca
      # ansible playbook to be run
      playbook: ansible/playbooks/on-hub-get-regional-ca.yml
      # per playbook timeout in seconds
      timeout: 234
      # verbosity: "-v"

  managedClusterGroups:
    region-one:
      name: region-one
      helmOverrides:
      - name: clusterGroup.isHubCluster
        value: false
      clusterSelector:
        matchLabels:
          clusterGroup: region-one

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main

#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: site.isHubCluster
#        value: false
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift
